@startuml ChecksumCalculationRoutineSeq


actor User
participant Hasher
participant HashAlgorithm

activate User #FFBBBB

User -> Hasher : GetChecksum(Collection<Stream> Files)
activate Hasher #FFBBBB
activate HashAlgorithm #FFBBBB

loop #Cyan CollectionIterator != end 
    alt #Gold fileEmpty
        Hasher --> User  : return 0x0000
    else #LightGreen File not empty
        loop FileIterator != FileEndIterator
            Hasher -> HashAlgorithm : TransformBlock(block)
            Hasher -> Hasher : OnUserUpdate(CompletedPercentage)
        end
        Hasher -> HashAlgorithm : TransformFinalBlock(block, 0, 0)

        Hasher -> HashAlgorithm : getComputedHash()
        HashAlgorithm --> Hasher : return result
        deactivate HashAlgorithm

        Hasher --> User : return result
        
        deactivate Hasher
    end
end
deactivate HashAlgorithm #FFBBBB
deactivate User #FFBBBB


@enduml